from pathlib import Path
from html import escape

ROOT = Path(__file__).parent

NAV = [('Home','index.html'),('Meridian','meridian.html'),('Plataforma','plataforma.html'),('Fundador','fundador.html'),('Diseños','disenos.html'),('Publicaciones','publicaciones.html'),('Cosmos','cosmos.html'),('Planes','planes.html'),('Chat IA','chat.html')]
TECH = [('MCP','mcp.html'),('OpenAI','openai.html'),('Claude','claude.html'),('Google','google.html'),('NVIDIA','nvidia.html'),('Cursor','cursor.html'),('GitHub','github.html'),('Vercel','vercel.html'),('Supabase','supabase.html'),('Notion','notion.html'),('Figma','figma.html'),('AWS','aws.html')]

pages = {
 'meridian.html': dict(kicker='MERIDIAN / ORIGIN', title='Diseño, IA<br><em>y dirección.</em>', desc='Meridian Design es un estudio y plataforma creativa para convertir ideas complejas en marcas, productos y sistemas que se pueden usar.', image='assets/visual-05.png', cta='Conocer Meridian App', href='plataforma.html', eyebrow='Una práctica independiente desde Santo Domingo.', blocks=[('01 / IDEA','Diseño con contexto','Cada proyecto comienza con una pregunta clara y termina en una experiencia que puede crecer.'),('02 / SYSTEM','Una capa operativa','Meridian conecta estrategia, identidad, contenido, automatización y tecnología en un solo lenguaje.'),('03 / MOTION','Que se mueva','Diseñamos sistemas que se sienten vivos: interfaces, campañas, objetos 3D y herramientas que invitan a actuar.')]),
 'plataforma.html': dict(kicker='MERIDIAN / PLATFORM', title='Todo tu trabajo.<br><em>Una superficie.</em>', desc='Meridian App reúne Chat IA, Workspace, Skills, MCP Connectors, Model Router, memoria y Creative Lab para trabajar con claridad.', image='assets/visual-06.png', cta='Abrir Meridian App', href='https://meridian-completo.vercel.app', eyebrow='Una plataforma modular para diseñar y operar.', blocks=[('APP','Meridian Workspace','Planifica, crea, investiga y transforma briefs en entregables.'),('MCP','Conectores con permiso','Conecta herramientas, datos y acciones con contexto y aprobaciones.'),('MODELS','Model Router','Elige el modelo correcto para cada tarea: velocidad, razonamiento, imagen o voz.')]),
 'fundador.html': dict(kicker='MERIDIAN / FOUNDER', title='Christian<br><em>De Jesus.</em>', desc='Diseñador gráfico, director creativo y fundador de Meridian Design y Christian Studio. Construyo marcas, sistemas y herramientas que conectan diseño con crecimiento.', image='assets/christian-junior-de-jesus.jpeg', cta='Trabajar juntos', href='contacto.html#formulario', eyebrow='Santo Domingo, República Dominicana / Design · AI · Product', blocks=[('01 / BIO','Una práctica entre disciplinas','Identidad visual, experiencias 3D, inteligencia artificial, marketing y productos digitales.'),('02 / NOW','Construyendo Meridian OS','Una plataforma para pensar, diseñar, automatizar, colaborar y avanzar con el contexto presente.'),('03 / CONTACT','Abrir conversación','Si tienes una idea, un sistema que ordenar o una marca que mover, hablemos.')]),
 'disenos.html': dict(kicker='MERIDIAN / WORK', title='Trabajos con<br><em>intención.</em>', desc='Una selección de identidades, interfaces, sistemas de contenido, experiencias 3D y prototipos que convierten estrategia en presencia.', image='assets/visual-07.jpg', cta='Solicitar un proyecto', href='contacto.html#formulario', eyebrow='Case studies / visual systems / prototypes', blocks=[('IDENTIDAD','Marcas que se reconocen','Dirección visual, sistemas tipográficos, campañas y guías que hacen consistente cada punto de contacto.'),('PRODUCTO','Experiencias que responden','Landing pages, dashboards, apps y objetos digitales con una jerarquía clara.'),('AI / 3D','Laboratorios vivos','Imágenes, movimiento, modelos y prototipos que amplían la imaginación sin perder el criterio.')]),
 'publicaciones.html': dict(kicker='MERIDIAN / RESEARCH', title='Ideas que<br><em>toman forma.</em>', desc='Investigaciones, notas de construcción, modelos, cultura visual y aprendizajes de producto. Un archivo normal, legible y abierto.', image='assets/visual-03.png', cta='Leer las publicaciones', href='#archivo', eyebrow='Research / notes / field reports', blocks=[('01','El brief como instrumento de claridad','Ensayo · 06 min · Cómo una pregunta bien formulada reduce el ruido.'),('02','Una interfaz también puede tener memoria','Investigación · 11 min · Contexto, documentos y continuidad.'),('03','Del prototipo a la experiencia viva','Caso de estudio · 09 min · Lo que ocurre después de publicar.')]),
 'cosmos.html': dict(kicker='MERIDIAN / COSMOS', title='Un sistema que<br><em>se conecta.</em>', desc='El universo de herramientas, servicios y protocolos que Meridian usa para diseñar, construir, almacenar, automatizar y publicar.', image='assets/visual-02.png', cta='Explorar tecnologías', href='#technologies', eyebrow='Connectors / protocols / tools', blocks=[('CONTEXT','Datos con sentido','Notion, Supabase, Google Drive y GitHub convierten información dispersa en contexto utilizable.'),('CREATE','Crear en conjunto','Figma, Canva, OpenAI, Claude y Google ayudan a pasar de la idea al prototipo.'),('SHIP','Publicar y medir','Vercel, AWS, Stripe, PostHog y Cloudflare hacen que el sistema llegue al mundo.')]),
 'chat.html': dict(kicker='MERIDIAN / CHAT', title='¿Qué quieres<br><em>construir?</em>', desc='Habla con Meridian para convertir una idea en un brief, una campaña, un sistema, una investigación o un próximo paso concreto.', image='assets/visual-01.png', cta='Abrir chat en la home', href='index.html#chat', eyebrow='Conversational workspace / context-first AI', blocks=[('BRIEF','Dale una dirección','Escribe una idea, sube un documento o pega un enlace. Meridian te ayuda a encontrar la forma.'),('BUILD','Trabaja con herramientas','Conecta MCP, Skills, modelos y documentos para avanzar sin perder el hilo.'),('SHIP','Termina con algo útil','Sal de la conversación con un plan, una página, una pieza o una decisión.')]),
}

tech_pages = {
 'mcp.html': ('MCP','Conecta el contexto<br><em>con acción.</em>','Model Context Protocol permite que Meridian conecte asistentes con datos, herramientas y aplicaciones con permisos claros.','assets/visual-06.png','https://modelcontextprotocol.io/','Conocer MCP'),
 'openai.html': ('OPENAI','Modelos para<br><em>ampliar ideas.</em>','Usamos OpenAI cuando necesitamos razonamiento, generación, agentes y herramientas que convierten intención en trabajo.','assets/visual-03.png','https://openai.com/','Visitar OpenAI'),
 'claude.html': ('ANTHROPIC / CLAUDE','Pensar con<br><em>precisión.</em>','Claude aporta escritura, análisis, prototipado y conversación larga para trabajos que necesitan criterio y contexto.','assets/visual-05.png','https://www.anthropic.com/','Visitar Anthropic'),
 'google.html': ('GOOGLE','Buscar, ver y<br><em>entender.</em>','Google conecta Meridian con búsqueda, Workspace, documentos, calendario y una capa multimodal para explorar el mundo.','assets/visual-01.png','https://ai.google/','Visitar Google AI'),
 'github.html': ('GITHUB','Construir en<br><em>público.</em>','GitHub guarda el código, el historial y la colaboración que permite que las ideas de Meridian se conviertan en sistemas versionados.','assets/visual-07.jpg','https://github.com/christiandejesus320-droid/Meridian-Design-2v1','Ver repositorio'),
 'vercel.html': ('VERCEL','Publicar con<br><em>velocidad.</em>','Vercel es la capa de despliegue y distribución de Meridian: del commit a una URL que puede ver el mundo.','assets/visual-02.png','https://vercel.com/','Visitar Vercel'),
 'supabase.html': ('SUPABASE','Memoria,<br><em>no ruido.</em>','Supabase aporta base de datos, autenticación, almacenamiento y una superficie confiable para que Meridian recuerde.','assets/visual-06.png','https://supabase.com/','Visitar Supabase'),
 'notion.html': ('NOTION','La biblioteca<br><em>del sistema.</em>','Notion organiza documentos, decisiones, briefs y conocimiento para que cada proyecto tenga una fuente de verdad.','assets/visual-05.png','https://www.notion.so/','Visitar Notion'),
 'figma.html': ('FIGMA','De la idea al<br><em>prototipo.</em>','Figma convierte dirección de arte y pensamiento de producto en interfaces compartibles, comentables y listas para construir.','assets/visual-03.png','https://www.figma.com/','Visitar Figma'),
 'nvidia.html': ('NVIDIA','Cómputo para<br><em>lo imposible.</em>','NVIDIA aporta la capa de cómputo acelerado que sostiene modelos, visión, simulación y experiencias de IA con baja latencia.','assets/visual-02.png','https://www.nvidia.com/en-us/about-nvidia/','Visitar NVIDIA'),
 'cursor.html': ('CURSOR','Código con<br><em>dirección.</em>','Cursor ayuda a convertir briefs de Meridian en código, iteraciones y productos que pueden revisarse, probarse y desplegarse.','assets/visual-07.jpg','https://cursor.com/','Visitar Cursor'),
 'aws.html': ('AWS','Infraestructura<br><em>que escala.</em>','AWS aporta servicios de nube, almacenamiento y ejecución para que las experiencias Meridian puedan crecer con control.','assets/visual-06.png','https://aws.amazon.com/about-aws/','Visitar AWS'),
}

def header(active=''):
    nav = ''.join(f'<a class="{("active" if label.lower()==active.lower() else "")}" href="{href}">{label}</a>' for label,href in NAV)
    tech_links = ''.join(f'<a href="{href}">{label}</a>' for label,href in TECH)
    return f'''<header class="landing-nav"><div class="landing-wrap"><a class="landing-logo" href="index.html">● MERIDIAN</a><nav>{nav}</nav><a class="landing-nav-cta" href="chat.html">Probar Meridian ↗</a></div></header>'''

def footer():
    tech = ''.join(f'<a href="{href}">{label}</a>' for label,href in TECH)
    return f'''<footer class="landing-footer"><div class="landing-wrap footer-grid"><div><a class="landing-logo" href="index.html">● MERIDIAN</a><p>Diseño, inteligencia y sistemas<br>para construir lo que sigue.</p></div><div><b>Explorar</b><a href="publicaciones.html">Investigación</a><a href="plataforma.html">Productos</a><a href="cosmos.html">Cosmos</a><a href="fundador.html">Fundador</a></div><div><b>Plataforma</b>{tech}</div><div><b>Contacto</b><a href="contacto.html#formulario">Trabajar juntos</a><a href="mailto:christiandejesus320@gmail.com">Email ↗</a><a href="https://github.com/christiandejesus320-droid" target="_blank" rel="noopener">GitHub ↗</a></div></div><div class="landing-wrap footer-bottom"><span>© 2026 Meridian Design</span><a href="legal.html">Privacidad / Términos</a></div></footer>'''

def shell(title, body, active=''):
    return f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Meridian Design — diseño, IA y sistemas creativos."><title>{escape(title)} — Meridian Design</title><link rel="stylesheet" href="meridian-landing.css"></head><body>{header(active)}<main>{body}</main>{footer()}</body></html>'''

def landing(filename, data):
    blocks = ''.join(f'<article class="landing-block"><span>{escape(a)}</span><h3>{escape(b)}</h3><p>{escape(c)}</p></article>' for a,b,c in data['blocks'])
    body = f'''<section class="landing-hero landing-wrap"><div class="landing-hero-copy"><span class="landing-kicker">{escape(data['kicker'])}</span><h1>{data['title']}</h1><p>{escape(data['desc'])}</p><div class="landing-actions"><a class="landing-button" href="{data['href']}">{escape(data['cta'])} →</a><a class="landing-text-link" href="cosmos.html">Ver el sistema ↗</a></div></div><figure class="landing-hero-image"><img src="{data['image']}" alt="Meridian Design — {escape(data['kicker'])}"><figcaption>{escape(data['eyebrow'])}</figcaption></figure></section><section class="landing-blocks landing-wrap"><div class="landing-section-label">MERIDIAN / PRINCIPLES</div>{blocks}</section><section class="landing-callout landing-wrap"><span class="landing-kicker">MERIDIAN / NEXT STEP</span><h2>Una buena idea<br><em>necesita movimiento.</em></h2><a class="landing-button" href="chat.html">Hablar con Meridian →</a></section>'''
    ROOT.joinpath(filename).write_text(shell(data['kicker'], body, data['kicker'].split('/')[1].strip()), encoding='utf-8')

for filename,data in pages.items(): landing(filename,data)

for filename,(kicker,title,desc,image,href,cta) in tech_pages.items():
    body=f'''<section class="landing-hero landing-wrap"><div class="landing-hero-copy"><span class="landing-kicker">MERIDIAN / {escape(kicker)}</span><h1>{title}</h1><p>{escape(desc)}</p><div class="landing-actions"><a class="landing-button" href="{href}" target="_blank" rel="noopener">{escape(cta)} ↗</a><a class="landing-text-link" href="cosmos.html">Ver todas las tecnologías ↗</a></div></div><figure class="landing-hero-image"><img src="{image}" alt="Meridian usa {escape(kicker)}"><figcaption>MERIDIAN / TECHNOLOGY PARTNER</figcaption></figure></section><section class="landing-blocks landing-wrap"><div class="landing-section-label">CÓMO LO USAMOS</div><article class="landing-block"><span>01 / CONTEXTO</span><h3>Una herramienta dentro de un sistema.</h3><p>Meridian no presenta tecnologías como logos aislados. Cada conexión tiene un propósito: investigar, crear, organizar, automatizar, proteger o publicar.</p></article><article class="landing-block"><span>02 / FLOW</span><h3>Brief → modelo → herramienta → resultado.</h3><p>La plataforma combina conversación, documentos, permisos y ejecución para que el trabajo sea visible y repetible.</p></article><article class="landing-block"><span>03 / LINK</span><h3>Conoce la fuente oficial.</h3><p>Explora la documentación y el producto original para entender la tecnología que Meridian integra.</p><a class="landing-text-link" href="{href}" target="_blank" rel="noopener">Abrir {escape(kicker)} ↗</a></article></section><section class="landing-callout landing-wrap"><span class="landing-kicker">MERIDIAN / STACK</span><h2>Las herramientas<br><em>deben servir a la idea.</em></h2><a class="landing-button" href="chat.html">Diseñar un flujo →</a></section>'''
    ROOT.joinpath(filename).write_text(shell(kicker,body,kicker), encoding='utf-8')

print(f'Generated {len(pages)+len(tech_pages)} landing pages')
